/// Pluggy's transaction categories, in English, as people here would call them. This is a
/// dictionary of the provider's taxonomy, not screen copy, so it lives in code next to the data
/// it translates. Unknown ones are shown as they came.
abstract final class Categories {
  static const uncategorized = 'UNCATEGORIZED';

  static String label(String? category) {
    if (category == null || category == uncategorized) {
      return 'Sem categoria';
    }
    return _labels[category.toLowerCase()] ?? category;
  }

  static const _labels = <String, String>{
    'income': 'Renda',
    'salary': 'Salário',
    'retirement': 'Aposentadoria',
    'entrepreneurial activities': 'Atividade empresarial',
    'government aid': 'Auxílio do governo',
    'non-recurring income': 'Renda extra',
    'loans and financing': 'Empréstimos e financiamentos',
    'loans': 'Empréstimos',
    'financing': 'Financiamentos',
    'investments': 'Investimentos',
    'interest': 'Rendimentos',
    'transfers': 'Transferências',
    'transfer - pix': 'Pix',
    'same person transfer': 'Entre minhas contas',
    'credit card payment': 'Pagamento de cartão',
    'legal obligations': 'Obrigações legais',
    'services': 'Serviços',
    'telecommunications': 'Telefone e internet',
    'internet': 'Internet',
    'mobile': 'Celular',
    'tv': 'TV',
    'education': 'Educação',
    'online courses': 'Cursos online',
    'university': 'Faculdade',
    'school': 'Escola',
    'wellness and fitness': 'Bem-estar',
    'wellness': 'Bem-estar',
    'gyms and fitness centers': 'Academia',
    'sports practice': 'Esportes',
    'leisure': 'Lazer',
    'entertainment': 'Entretenimento',
    'tickets': 'Ingressos',
    'video streaming': 'Streaming de vídeo',
    'music streaming': 'Streaming de música',
    'gaming': 'Jogos',
    'shopping': 'Compras',
    'online shopping': 'Compras online',
    'electronics': 'Eletrônicos',
    'pet supplies and vet': 'Pets',
    'clothing': 'Roupas',
    'kids and toys': 'Infantil',
    'bookstore': 'Livraria',
    'office supplies': 'Papelaria',
    'digital services': 'Serviços digitais',
    'food and drinks': 'Alimentação',
    'groceries': 'Mercado',
    'eating out': 'Restaurantes',
    'food delivery': 'Delivery',
    'travel': 'Viagem',
    'airport and airlines': 'Passagens aéreas',
    'accommodation': 'Hospedagem',
    'mileage programs': 'Milhas',
    'bus tickets': 'Passagens de ônibus',
    'donations': 'Doações',
    'gambling': 'Apostas',
    'lottery': 'Loteria',
    'online bet': 'Apostas online',
    'taxes': 'Impostos',
    'income taxes': 'Imposto de renda',
    'taxes on investments': 'Impostos sobre investimentos',
    'tax on financial operations': 'IOF',
    'bank fees': 'Tarifas bancárias',
    'account fees': 'Tarifas de conta',
    'wire transfer fees': 'Tarifas de transferência',
    'credit card fees': 'Tarifas do cartão',
    'late payment and overdraft costs': 'Juros e multas',
    'housing': 'Moradia',
    'rent': 'Aluguel',
    'utilities': 'Contas da casa',
    'water': 'Água',
    'electricity': 'Luz',
    'gas': 'Gás',
    'urban land and building tax': 'IPTU',
    'healthcare': 'Saúde',
    'dentist': 'Dentista',
    'pharmacy': 'Farmácia',
    'optometry': 'Ótica',
    'hospital clinics and labs': 'Clínicas e exames',
    'transportation': 'Transporte',
    'taxi and ride-hailing': 'Táxi e apps',
    'public transportation': 'Transporte público',
    'car rental': 'Aluguel de carro',
    'bicycle': 'Bicicleta',
    'automotive': 'Automóvel',
    'gas stations': 'Combustível',
    'parking': 'Estacionamento',
    'tolls and in vehicle payment': 'Pedágio',
    'vehicle ownership taxes and fees': 'IPVA e taxas',
    'vehicle maintenance': 'Manutenção do carro',
    'traffic tickets': 'Multas de trânsito',
    'insurance': 'Seguros',
    'life insurance': 'Seguro de vida',
    'home insurance': 'Seguro residencial',
    'health insurance': 'Plano de saúde',
    'vehicle insurance': 'Seguro do carro',
    'other': 'Outros',
  };
}
